In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("car data.csv")
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [3]:
df.head(10)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,0
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,0
7,s cross,2015,6.50,8.61,33429,Diesel,Dealer,Manual,0
8,ciaz,2016,8.75,8.89,20273,Diesel,Dealer,Manual,0
9,ciaz,2015,7.45,8.92,42367,Diesel,Dealer,Manual,0

In [4]:
df.tail(10)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
291,brio,2015,5.40,6.10,31427,Petrol,Dealer,Manual,0
292,jazz,2016,6.40,8.40,12000,Petrol,Dealer,Manual,0
293,city,2010,3.25,9.90,38000,Petrol,Dealer,Manual,0
294,amaze,2014,3.75,6.80,33019,Petrol,Dealer,Manual,0
295,city,2015,8.55,13.09,60076,Diesel,Dealer,Manual,0
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [5]:
df.shape

(301, 9)

In [6]:
df.duplicated().sum()

2

In [7]:
dfa=df.drop_duplicates(subset=None,keep='first',inplace=False)
dfa

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [8]:
dfa.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [9]:
dfa.info()

<class 'pandas.core.frame.DataFrame'>
Index: 299 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       299 non-null    object
 1   Year           299 non-null    int64
 2   Selling_Price  299 non-null    float64
 3   Present_Price  299 non-null    float64
 4   Kms_Driven     299 non-null    int64
 5   Fuel_Type      299 non-null    object
 6   Seller_Type    299 non-null    object
 7   Transmission   299 non-null    object
 8   Owner          299 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 23.4+ KB

In [10]:
import datetime
# Get the current year
current_year = datetime.datetime.now().year

# Calculate the number of years from each year to the current year
dfa['no_of_year'] = current_year - dfa['Year']
dfa

C:\Users\NAND\AppData\Local\Temp\ipykernel_13772\2242918151.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfa['no_of_year'] = current_year - dfa['Year']

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,no_of_year
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,10
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,11
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,7
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,13
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,10
...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0,8
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0,9
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0,15
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0,7
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0,8

EDA(Exploratory Data Analysis)

In [12]:
car_name_wise=dfa.Car_Name.value_counts()
car_name_wise

Car_Name
city                        26
corolla altis               16
verna                       14
brio                        10
fortuner                    10
                            ..
Honda CB Trigger             1
Yamaha FZ S                  1
Bajaj Pulsar 135 LS          1
Activa 4g                    1
Bajaj Avenger Street 220     1
Name: count, Length: 98, dtype: int64

In [13]:
year_wise=dfa.Year.value_counts()
year_wise

Year
2015    60
2016    49
2014    38
2017    35
2013    33
2012    23
2011    19
2010    15
2008     7
2009     6
2006     4
2005     4
2003     2
2007     2
2018     1
2004     1
Name: count, dtype: int64

In [14]:
fuel_wise=dfa.Fuel_Type.value_counts()
fuel_wise

Fuel_Type
Petrol    239
Diesel     58
CNG         2
Name: count, dtype: int64

In [15]:
dfa=dfa.drop(columns=['Car_Name'])
dfa.head()

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,no_of_year
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,10
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,11
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,7
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,13
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,10

In [16]:
dfa= pd.get_dummies(dfa,drop_first=True)
dfa

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,no_of_year,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,2014,3.35,5.59,27000,0,10,False,True,False,True
1,2013,4.75,9.54,43000,0,11,True,False,False,True
2,2017,7.25,9.85,6900,0,7,False,True,False,True
3,2011,2.85,4.15,5200,0,13,False,True,False,True
4,2014,4.60,6.87,42450,0,10,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,0,8,True,False,False,True
297,2015,4.00,5.90,60000,0,9,False,True,False,True
298,2009,3.35,11.00,87934,0,15,False,True,False,True
299,2017,11.50,12.50,9000,0,7,True,False,False,True
300,2016,5.30,5.90,5464,0,8,False,True,False,True

In [17]:
from sklearn.preprocessing import LabelEncoder
# Now you can proceed with splitting your data and fitting the model
X = dfa.drop('Selling_Price', axis=1)
Y = dfa['Selling_Price']

In [18]:
from sklearn.model_selection import train_test_split # split x & y into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

In [19]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor(max_depth=3)

In [20]:
dt.fit(X_train,Y_train)

DecisionTreeRegressor(max_depth=3)

In [21]:
print(dt.score(X_train,Y_train))
print(dt.score(X_test, Y_test))

0.901777544224257
0.7117504557457717

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Create and train the Linear Regression model
model_lr = LinearRegression()
model_lr.fit(X_train, Y_train)

# Make predictions
y_pred_lr = model_lr.predict(X_test)

# Calculate performance metrics
mae_lr = mean_absolute_error(Y_test, y_pred_lr)
mse_lr = mean_squared_error(Y_test, y_pred_lr)
rmse_lr = np.sqrt(mse_lr)
mape_lr = np.mean(np.abs((Y_test - y_pred_lr) / np.abs(Y_test)))
accuracy_lr = 100 * (1 - mape_lr)

# Print the performance metrics for Linear Regression
print('Linear Regression Metrics:')
print('Mean Absolute Error (MAE):', mae_lr)
print('Mean Squared Error (MSE):', mse_lr)
print('Root Mean Squared Error (RMSE):', rmse_lr)
print('Mean Absolute Percentage Error (MAPE):', round(mape_lr * 100, 2))
print('Accuracy:', round(accuracy_lr, 2))

Linear Regression Metrics:
Mean Absolute Error (MAE): 1.1892927467364591
Mean Squared Error (MSE): 4.442020489589826
Root Mean Squared Error (RMSE): 2.107610137001107
Mean Absolute Percentage Error (MAPE): 138.67
Accuracy: -38.67

In [23]:
from sklearn.tree import DecisionTreeRegressor 

# Create and train the Linear Regression model
model = DecisionTreeRegressor()
model.fit(X_train, Y_train)

# Make predictions
y_pred = model.predict(X_test)

# Calculate performance metrics
mae = mean_absolute_error(Y_test, y_pred)
mse = mean_squared_error(Y_test, y_pred)
rmse = np.sqrt(mse)
mape = np.mean(np.abs((Y_test - y_pred) / np.abs(Y_test)))
accuracy = 100 * (1 - mape)

# Print the performance metrics for Linear Regression
print('Mean Absolute Error (MAE):', mae)
print('Mean Squared Error (MSE):', mse)
print('Root Mean Squared Error (RMSE):', rmse)
print('Mean Absolute Percentage Error (MAPE):', round(mape * 100, 2))
print('Accuracy:', round(accuracy, 2))

Mean Absolute Error (MAE): 1.3537777777777777
Mean Squared Error (MSE): 17.416544444444444
Root Mean Squared Error (RMSE): 4.173313365234445
Mean Absolute Percentage Error (MAPE): 25.03
Accuracy: 74.97

In [24]:
from sklearn.ensemble import RandomForestRegressor

# Create and train the Linear Regression model
model_rf = RandomForestRegressor(n_estimators=100, random_state=42)
model_rf.fit(X_train, Y_train)

# Make predictions
y_pred_rf = model_rf.predict(X_test)

# Calculate performance metrics
mae_rf = mean_absolute_error(Y_test, y_pred_rf)
mse_rf = mean_squared_error(Y_test, y_pred_rf)
rmse_rf = np.sqrt(mse_rf)
mape_rf = np.mean(np.abs((Y_test - y_pred_rf) / np.abs(Y_test)))
accuracy_rf = 100 * (1 - mape_rf)

# Print the performance metrics for Linear Regression
print('Random Forest Metrics:')
print('Mean Absolute Error (MAE):', mae_rf)
print('Mean Squared Error (MSE):', mse_rf)
print('Root Mean Squared Error (RMSE):', rmse_rf)
print('Mean Absolute Percentage Error (MAPE):', round(mape_rf * 100, 2))
print('Accuracy:', round(accuracy_rf, 2))

Random Forest Metrics:
Mean Absolute Error (MAE): 0.6448799999999999
Mean Squared Error (MSE): 2.185486540666667
Root Mean Squared Error (RMSE): 1.4783391155843326
Mean Absolute Percentage Error (MAPE): 15.54
Accuracy: 84.46

In [25]:
import xgboost as xgb

# Create and train the Linear Regression model
model_xgb = xgb.XGBRegressor()
model_xgb.fit(X_train, Y_train)

# Make predictions
y_pred_xgb = model_xgb.predict(X_test)

# Calculate performance metrics
mae_xgb = mean_absolute_error(Y_test, y_pred_xgb)
mse_xgb = mean_squared_error(Y_test, y_pred_xgb)
rmse_xgb = np.sqrt(mse_xgb)
mape_xgb = np.mean(np.abs((Y_test - y_pred_xgb) / np.abs(Y_test)))
accuracy_xgb = 100 * (1 - mape_xgb)

# Print the performance metrics for Linear Regression
print('XGBoost Metrics:')
print('Mean Absolute Error (MAE):', mae_xgb)
print('Mean Squared Error (MSE):', mse_xgb)
print('Root Mean Squared Error (RMSE):', rmse_xgb)
print('Mean Absolute Percentage Error (MAPE):', round(mape_xgb * 100, 2))
print('Accuracy:', round(accuracy_xgb, 2))

XGBoost Metrics:
Mean Absolute Error (MAE): 0.8063480349116855
Mean Squared Error (MSE): 3.3636862914724763
Root Mean Squared Error (RMSE): 1.8340355207771948
Mean Absolute Percentage Error (MAPE): 18.58
Accuracy: 81.42

In [26]:
import pickle
from sklearn.ensemble import RandomForestRegressor

# Example: Train a model (XGBoost Regressor as an example)
model_rf = RandomForestRegressor(n_estimators=100, random_state=42)
model_rf.fit(X_train, Y_train)

# Save the trained model to a file using pickle
with open('car.pkl', 'wb') as file:
    pickle.dump(model_rf, file)

print("Model saved successfully.")

Model saved successfully.

In [27]:

streamlit_code = """

import streamlit as st
import pickle
import numpy as np
import pandas as pd

# Load the trained model and scaler
with open('car.pkl', 'rb') as model_file:
    model = pickle.load(model_file)

# Streamlit app
st.title("Car Price Prediction")
st.sidebar.header("Input Features")

# Sidebar inputs
year = st.sidebar.slider("Year", min_value=2000, max_value=2022, value=2015)
present_price = st.sidebar.number_input("Present Price (in lakhs)", min_value=0.0, value=6.0)
kms_driven = st.sidebar.number_input("Kms Driven", min_value=0)
fuel_type = st.sidebar.selectbox("Fuel Type", ['Petrol', 'Diesel', 'CNG'])
seller_type = st.sidebar.selectbox("Seller Type", ['Dealer', 'Individual'])
transmission = st.sidebar.radio("Transmission", ['Manual', 'Automatic'])
owner = st.sidebar.slider("Owner", min_value=0, max_value=3, value=0)
no_of_years = st.sidebar.slider("No. of Years", min_value=1, max_value=20, value=5)

# Create input DataFrame with correct feature names and order
input_data = pd.DataFrame({
    'Year': [year],
    'Present_Price': [present_price],
    'Kms_Driven': [kms_driven],
    'Owner': [owner],
    'no_of_year': [no_of_years],
    'Fuel_Type': [fuel_type],
    'Seller_Type': [seller_type],
    'Transmission': [transmission]
})

# Map categorical variables to dummy variables
input_data = pd.get_dummies(input_data, drop_first=True)

# Ensure all required columns are present and in the correct order
expected_columns = ['Year', 'Present_Price', 'Kms_Driven', 'Owner', 'no_of_year',
                    'Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Seller_Type_Individual', 'Transmission_Manual']

# Reorder columns to match the expected order
input_data = input_data.reindex(columns=expected_columns, fill_value=0)

# Make prediction
predicted_price = model.predict(input_data)

# Display prediction
st.write(f"Predicted Selling Price: {predicted_price[0]:.2f} lakhs")
"""
# Specify the file path where the hrapp.py file will be saved
file_path = 'carapp.py'

# Write the content to the file
with open(file_path, 'w') as file:
    file.write(streamlit_code)

print(f"File '{file_path}' has been saved.")

File 'carapp.py' has been saved.